[Rule Tuning] Merge and Delete duplicate rules for Registration Utilities
elastic/detection-rules pull request #1028
Opened 2021-03-10 11:11 UTC by Samirbous

## Issues

Resolves https://github.com/elastic/detection-rules/issues/1027

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-03-17 02:43 UTC, brokensound77 requested changes

2021-03-17 02:43 UTC, brokensound77 commented on rules/windows/execution_via_net_com_assemblies.toml
> -[metadata]
I just created a PR for this, ref: #1050

2021-03-17 02:43 UTC, brokensound77 commented on rules/windows/execution_register_server_program_connecting_to_the_internet.toml
> +         (process.parent.name : "msiexec.exe" or process.parent.executable:("C:\\Program Files (x86)\\*.exe", "C:\\Program Files\\*.exe"))
```suggestion
         (process.parent.name : "msiexec.exe" or process.parent.executable : ("C:\\Program Files (x86)\\*.exe", "C:\\Program Files\\*.exe"))
```

2021-03-17 05:38 UTC, brokensound77 commented on rules/windows/execution_via_net_com_assemblies.toml
> -[metadata]
restore this file and run `python -m detection_rules dev deprecate-rule <rule-path>`.

2021-03-17 09:53 UTC, Samirbous commented on rules/windows/execution_via_net_com_assemblies.toml
> -[metadata]
nice, done.

2021-03-18 15:34 UTC, threat-punter approved these changes

2021-03-18 16:56 UTC, brokensound77 approved these changes
Thanks for making those changes

2021-03-19 09:05 UTC, merged