Fix rule filenames during packaging
elastic/detection-rules pull request #1158
Opened 2021-05-04 16:44 UTC by brokensound77

## Issues
No issue, just small fixes to issues noticed during packaging

## Summary
Bug fixes for things needed during packaging and testing

*Will need backport to 7.13 branch*

2021-05-04 16:48 UTC, rw-access requested changes
let's sync up offline

2021-05-04 16:48 UTC, rw-access commented on detection_rules/rule.py
> +        # get the hash of the API dict without the version by default, otherwise it'll always be dirty.
wait no. This causes a bad feedback loop

2021-05-04 17:10 UTC, rw-access commented on detection_rules/rule.py
> +        # get the hash of the API dict without the version by default, otherwise it'll always be dirty.
nevermind, optional is good

2021-05-04 17:10 UTC, rw-access approved these changes

2021-05-04 17:10 UTC, rw-access commented
Also, if 7.13 hasn't deviated from `main` yet, then you can safely merge `main` -> `7.13` locally

2021-05-05 19:23 UTC, brokensound77 commented
> Also, if 7.13 hasn't deviated from `main` yet, then you can safely merge `main` -> `7.13` locally

It has deviated a bit, so I can cherry pick back

2021-05-05 19:27 UTC, merged