Persistence new or modified federation domain.toml
elastic/detection-rules pull request #1212
Opened 2021-05-17 19:03 UTC by austinsonger

## Issues

Resolves #1162

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-06-22 18:00 UTC, brokensound77 commented on rules/microsoft-365/persistence_new_or_modified_federation_domain.toml
> +rule_id = "684554fc-0777-47ce-8c9b-3d01f198d7f8"
Please provide references if possible

2021-06-23 00:03 UTC, austinsonger commented on rules/microsoft-365/persistence_new_or_modified_federation_domain.toml
> +author = ["Elastic", "Austin Songer"]
Oh okay. Good to know.

2021-09-22 12:45 UTC, w0rk3r requested changes
Hey @austinsonger, left a requested change, after that, LGTM

2021-09-22 12:45 UTC, w0rk3r commented on rules/integrations/o365/persistence_new_or_modified_federation_domain.toml
> +id = "TA0003"
This one fits better:
https://attack.mitre.org/techniques/T1484 and https://attack.mitre.org/techniques/T1484/002/

2021-09-29 12:15 UTC, w0rk3r approved these changes

2021-09-29 12:16 UTC, merged