[New Rule] GCP Kubernetes Rolebindings Creation
elastic/detection-rules pull request #1267
Opened 2021-06-06 16:46 UTC by austinsonger

## Issues

Resolves #1191

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-10-12 22:50 UTC, w0rk3r requested changes
Left some points we need to clarify, thanks!

2021-10-12 22:50 UTC, w0rk3r commented on rules/integrations/gcp/credential_access_gcp_kubernetes_rolebindings_creation.toml
> +
Missing Integration

2021-10-12 22:50 UTC, w0rk3r commented on .gitignore
> +/elastic-detection-cli
```suggestion
```

2021-10-12 22:50 UTC, w0rk3r commented on rules/integrations/gcp/credential_access_gcp_kubernetes_rolebindings_creation.toml
> +author = ["Elastic","Austin Songer"]
```suggestion
author = ["Elastic", "Austin Songer"]
```

2021-10-12 22:50 UTC, w0rk3r commented on rules/integrations/gcp/credential_access_gcp_kubernetes_rolebindings_creation.toml
> +Identifies the creation or patching of potential malicious rolebinding.
How we differentiate from normal activity? If not, needs to be reformulated, also needs some context around rolebindings

2021-10-12 22:50 UTC, w0rk3r commented on rules/integrations/gcp/credential_access_gcp_kubernetes_rolebindings_creation.toml
> +name = "GCP "
Missing Rule name

2021-10-12 22:50 UTC, w0rk3r commented on rules/integrations/gcp/credential_access_gcp_kubernetes_rolebindings_creation.toml
> +    "https://cloud.google.com/kubernetes-engine/docs/how-to/audit-logging",
Needs a more specific/related reference

2021-10-12 22:50 UTC, w0rk3r commented on rules/integrations/gcp/credential_access_gcp_kubernetes_rolebindings_creation.toml
> +
Can't see a case for Credential Access here

2021-10-15 18:27 UTC, brokensound77 commented on rules/integrations/gcp/privilege_escalation_gcp_kubernetes_rolebindings_created_or_patched.toml
> +event.dataset:(googlecloud.audit or gcp.audit) and event.action: (io.k8s.authorization.rbac.v*.clusterrolebindings.create or
```suggestion
event.dataset:(googlecloud.audit or gcp.audit) and event.action:(io.k8s.authorization.rbac.v*.clusterrolebindings.create or 
```

2021-10-15 18:42 UTC, merged

2022-01-22 23:50 UTC, CyberTaoFlow commented
@austinsonger Can we have the system:addon-manager user provided as an exception by default for this otherwise its quite noisy.