[New Rule] Microsoft 365 - Mass download by a single user
elastic/detection-rules pull request #1348
Opened 2021-07-15 22:32 UTC by austinsonger

## Issues

#1318

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-07-24 02:22 UTC, austinsonger commented
It looks like I created these rules before elastic is able to trigger the detection. Should I just leave this open until the integration happens?

https://github.com/elastic/integrations/issues/1131

2021-10-05 16:13 UTC, w0rk3r requested changes
Leaving some comments/requests here. Thanks for the contribution!

2021-10-05 16:13 UTC, w0rk3r commented on rules/integrations/o365/impact_microsoft_365_mass_download_by_a_single_user.toml
> +
Missing Integration

2021-10-05 16:13 UTC, w0rk3r commented on rules/integrations/o365/impact_microsoft_365_mass_download_by_a_single_user.toml
> +name = "Microsoft 365 - Mass download by a single user"
```suggestion
name = "Microsoft 365 Mass download by a single user"
```

2021-10-05 16:13 UTC, w0rk3r commented on rules/integrations/o365/impact_microsoft_365_mass_download_by_a_single_user.toml
> +id = "T1485"
Can't see a case for data destruction on this one

2021-10-05 16:13 UTC, w0rk3r commented on rules/integrations/o365/impact_microsoft_365_mass_download_by_a_single_user.toml
> +id = "TA0040"
I think we can remove the technique here and change the tactic to Exfiltration: https://attack.mitre.org/tactics/TA0010/

2021-10-13 17:11 UTC, w0rk3r commented
Hey @austinsonger, any updates on this one?

2021-10-15 19:01 UTC, merged