AWS ElastiCache Security Group Created
elastic/detection-rules pull request #1363
Opened 2021-07-20 00:36 UTC by austinsonger

## Issues

Resolves #1354

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-09-29 17:22 UTC, w0rk3r requested changes
Hey @austinsonger, thanks for the contribution. Here are some required changes before we merge this one

2021-09-29 17:22 UTC, w0rk3r commented on rules/integrations/aws/persistence_elasticache_security_group_creation.toml
> +references = ["https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/Welcome.html"]
```suggestion
references = ["https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateCacheSecurityGroup.html"]
```

2021-09-29 17:22 UTC, w0rk3r commented on rules/integrations/aws/persistence_elasticache_security_group_creation.toml
> +reference = "https://attack.mitre.org/tactics/TA0003/"
```suggestion
[[rule.threat.technique]]
id = "T1562"
name = "Impair Defenses"
reference = "https://attack.mitre.org/techniques/T1562/"

  [[rule.threat.technique.subtechnique]]
  id = "T1562.007"
  name = "Disable or Modify Cloud Firewall"
  reference = "https://attack.mitre.org/techniques/T1562/007/"

[rule.threat.tactic]
name = "Defense Evasion"
id = "TA0005"
reference = "https://attack.mitre.org/tactics/TA0005/"
```

This one fits better in this case, also we need to rename the rule to `defense_evasion_elasticache_security_group_creation.toml`

2021-10-01 11:46 UTC, w0rk3r commented on rules/integrations/aws/persistence_elasticache_security_group_creation.toml
> +reference = "https://attack.mitre.org/tactics/TA0003/"
This one still needs to be fixed/discussed.

2021-10-01 14:39 UTC, w0rk3r approved these changes
LGTM

2021-10-01 14:40 UTC, w0rk3r requested changes

2021-10-01 14:40 UTC, w0rk3r commented on rules/integrations/aws/defense_evasion_elasticache_security_group_creation.toml
> +updated_date = "2021/10/01"
```suggestion
updated_date = "2021/10/01"
integration = "aws"
```

2021-10-01 14:40 UTC, w0rk3r commented on rules/integrations/aws/defense_evasion_elasticache_security_group_creation.toml
> +updated_date = "2021/10/01"
Missed this one, after this, LGTM

2021-10-01 14:43 UTC, w0rk3r approved these changes
Thanks! LGTM

2021-10-04 18:36 UTC, brokensound77 commented on rules/integrations/aws/defense_evasion_elasticache_security_group_creation.toml
> +event.dataset:aws.cloudtrail and  event.provider:elasticache.amazonaws.com and event.action:"Create Cache Security Group" and
```suggestion
event.dataset:aws.cloudtrail and event.provider:elasticache.amazonaws.com and event.action:"Create Cache Security Group" and 
```

2021-10-04 18:37 UTC, brokensound77 approved these changes
👍

2021-10-05 17:00 UTC, merged