[New Rule] AWS ElastiCache Security Group Modified or Deleted
elastic/detection-rules pull request #1364
Opened 2021-07-20 00:36 UTC by austinsonger

## Issues

Resolves #1352

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-09-29 17:59 UTC, w0rk3r requested changes
Just one requested change, then LGTM.

2021-09-29 17:59 UTC, w0rk3r commented on rules/integrations/aws/impact_elasticache_security_group_modified_or_deleted.toml
> +reference = "https://attack.mitre.org/tactics/TA0040/"
```suggestion
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1562"
name = "Impair Defenses"
reference = "https://attack.mitre.org/techniques/T1562/"

  [[rule.threat.technique.subtechnique]]
  id = "T1562.007"
  name = "Disable or Modify Cloud Firewall"
  reference = "https://attack.mitre.org/techniques/T1562/007/"

[rule.threat.tactic]
name = "Defense Evasion"
id = "TA0005"
reference = "https://attack.mitre.org/tactics/TA0005/"
```

This one fits better in this one, we also need to rename the rule to `defense_evasion_elasticache_security_group_modified_or_deleted.toml`

2021-10-01 11:49 UTC, w0rk3r commented on rules/integrations/aws/impact_elasticache_security_group_modified_or_deleted.toml
> +reference = "https://attack.mitre.org/tactics/TA0040/"
The file needs to be renamed to the above to correspond with the tactic.

2021-10-01 14:45 UTC, w0rk3r approved these changes
LGTM

2021-10-04 18:35 UTC, brokensound77 approved these changes
👍

2021-10-04 18:38 UTC, merged