[New Rule] - Defense Evasion II HttpLogging Disabled
elastic/detection-rules pull request #142
Opened 2020-08-14 13:52 UTC by Samirbous

## Issues

https://github.com/elastic/detection-rules/issues/141

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2020-09-16 20:45 UTC, threat-punter commented on rules/windows/defense_evasion_iis_httplogging_disabled.toml
> +ecs_version = ["1.5.0"]
```suggestion
creation_date = "2020/08/14"
ecs_version = ["1.6.0"]
```

2020-09-16 20:50 UTC, threat-punter commented on rules/windows/defense_evasion_iis_httplogging_disabled.toml
> +measure. Verify the legitimacy context of this change.
```suggestion
Identifies when Internet Information Services (IIS) HTTP Logging is disabled. An attacker with IIS server access via a webshell or other mechanism can disable HTTP Logging as an effective anti-forensics measure.
```

2020-09-16 20:53 UTC, threat-punter commented on rules/windows/defense_evasion_iis_httplogging_disabled.toml
> +measure. Verify the legitimacy context of this change.
If you know what level of access is required to disable HTTP Logging on an IIS server, can we put that in the description of the rule too?

I'd recommend moving the sentence below to the notes field of the rule, as the description field is typically used to describe the behavior that the rule detects and the motive for why an attacker might execute the technique. The notes field contains information that's helpful for analysts to triage/investigate the alert.

> Verify the legitimacy context of this change.

2020-09-16 20:54 UTC, threat-punter commented on rules/windows/defense_evasion_iis_httplogging_disabled.toml
> +name = "IIS HttpLogging Disabled"
```suggestion
name = "IIS HTTP Logging Disabled"
```

2020-09-16 20:55 UTC, threat-punter requested changes
I really like this new rule. I left a few comments and suggestions for your review. 👍

2020-09-22 12:58 UTC, Samirbous commented on rules/windows/defense_evasion_iis_httplogging_disabled.toml
> +measure. Verify the legitimacy context of this change.
agree, removed it (no value, description is quite clear logging disabled)

2020-09-22 21:34 UTC, threat-punter approved these changes

2020-09-29 06:28 UTC, brokensound77 commented on rules/windows/defense_evasion_iis_httplogging_disabled.toml
> +index = ["winlogbeat-*", "logs-endpoint.events.*"]
```suggestion
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*"]
```

2020-09-29 06:29 UTC, brokensound77 approved these changes
Last comment, then LGTM 👍

2020-09-29 09:39 UTC, merged