[New Rule] AWS Default Policy Version Modified
elastic/detection-rules pull request #1520
Opened 2021-10-04 02:50 UTC by austinsonger

## Issues

Resolves #1500

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-11-25 16:41 UTC, w0rk3r requested changes

2021-11-25 16:41 UTC, w0rk3r commented on rules/integrations/aws/privilege_escalation_default_policy_version_modified.toml
> +set an old version of the policy as the default policy and then gain full admin privilege over the AWS account.
```suggestion
Identifies when an IAM policy default version is modified. An adversary could change the IAM policy's default version
and potentially gain full administrator access to the AWS account.
```

2021-11-25 16:41 UTC, w0rk3r commented on rules/integrations/aws/privilege_escalation_default_policy_version_modified.toml
> +    Default Policy Version could be modified by a system administrator. Verify whether the user identity,
```suggestion
    The IAM Policy Default Version could be modified by a system administrator. Verify whether the user identity, 
```

2021-11-25 16:41 UTC, w0rk3r commented on rules/integrations/aws/privilege_escalation_default_policy_version_modified.toml
> +event.action:SetDefaultPolicyVersion and event.outcome:success
@austinsonger we are going to need of an event of this action to proceed.

2021-12-12 22:35 UTC, w0rk3r commented
Closing this one due to the lack of requested events for testing and confirmation of effectiveness. Please feel free to open a new PR with the requested/related events if we progress on this. I am leaving the Issue open for now.

2021-12-15 00:00 UTC, austinsonger commented
@w0rk3r Can you reopen this, so I can close it because I can reopen it. Because if you close it, I can't reopen the Pull Request.

2021-12-15 16:53 UTC, closed without merging