[New Rule] Azure Kubernetes Role/ClusterRole Modified or Deleted
elastic/detection-rules pull request #1578
Opened 2021-10-18 20:39 UTC by austinsonger

## Issues

Resolves #1278

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-10-18 20:44 UTC, w0rk3r commented on rules/integrations/azure/privilege_escalation_azure_kubernetes_role_modified_or_deleted.toml
> +Identifies when a Azure Kubernetes Role/ClusterRole is Modifiedn or Deleted.
Typo, + needs elaboration, why this should be monitored?

2021-10-18 20:45 UTC, w0rk3r commented on rules/integrations/azure/privilege_escalation_azure_kubernetes_role_modified_or_deleted.toml
> +name = "Azure Kubernetes Role/ClusterRole Modified or Deleted"
What is the difference? There is any term that cover them both?

2021-10-18 20:45 UTC, w0rk3r commented on rules/integrations/azure/privilege_escalation_azure_kubernetes_role_modified_or_deleted.toml
> +         MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/RBAC.AUTHORIZATION.K8S.IO/ROLES/ESCALATE/ACTION) and
Quotes

2021-10-20 09:40 UTC, w0rk3r requested changes

2021-10-20 09:40 UTC, w0rk3r commented on rules/integrations/azure/privilege_escalation_azure_kubernetes_role_modified_or_deleted.toml
> +	("MICROSOFT.KUBERNETES/CONNECTEDCLUSTERS/RBAC.AUTHORIZATION.K8S.IO/CLUSTERROLES/WRITE" or
Same requests as https://github.com/elastic/detection-rules/pull/1576#discussion_r732591915

2021-12-14 05:02 UTC, austinsonger commented
I will be going on leave for the next 3 weeks. I'm going to close this and reopen when I have time.

2021-12-14 05:02 UTC, closed without merging