[New Rule] Clearing Windows Console History
elastic/detection-rules pull request #1623
Opened 2021-11-23 02:26 UTC by austinsonger

## Issues

Resolves #1622 

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-11-23 11:42 UTC, w0rk3r requested changes
Left some changes. Thanks

2021-11-23 11:42 UTC, w0rk3r commented on rules/windows/defense_evasion_clearing_windows_console_history.toml
> +     ("pwsh.exe", "powershell.exe", "powershell_ise.exe") and
```suggestion
     ("pwsh.dll", "powershell.exe", "powershell_ise.exe") and
```
As we saw last time, the original name for pwsh.exe is pwsh.dll

2021-11-23 11:42 UTC, w0rk3r commented on rules/windows/defense_evasion_clearing_windows_console_history.toml
> +Identifies when an user attempts to clear console history. An adversary may clear the command history of a compromised account to conceal
```suggestion
Identifies when a user attempts to clear console history. An adversary may clear the command history of a compromised account to conceal
```

2021-11-23 11:42 UTC, w0rk3r commented on rules/windows/defense_evasion_clearing_windows_console_history.toml
> +	 process.args : ("Set-PSReadlineOption","Remove-Item","*ConsoleHost*history*","Clear-History","-HistorySaveStyle","SaveNothing")
This need to be elaborated. Same problem as https://github.com/elastic/detection-rules/pull/1565#discussion_r755014400

2021-11-24 11:31 UTC, w0rk3r requested changes

2021-11-24 11:31 UTC, w0rk3r commented on rules/windows/defense_evasion_clearing_windows_console_history.toml
> +	 process.args : ("Set-PSReadlineOption","-HistorySaveStyle","SaveNothing"))
This still an OR condition, for example. this query would match any command line that contains `Remove-Item` alone. You need an AND condition here.

See [this](https://github.com/elastic/detection-rules/pull/1565#discussion_r755959162) comment on another PR, you can adjust this one based on that query

2021-11-24 22:17 UTC, w0rk3r approved these changes
Just some additional changes on the query, then LGTM

2021-11-24 22:17 UTC, w0rk3r commented on rules/windows/defense_evasion_clearing_windows_console_history.toml
> +	 process.args : "Set-PSReadlineOption" and process.args : ("-HistorySaveStyle","SaveNothing")
```suggestion
process where event.action == "start" and
  (process.name : ("powershell.exe", "pwsh.exe", "powershell_ise.exe") or process.pe.original_file_name == "PowerShell.EXE") and
     (process.args : "*Clear-History*" or
     (process.args : ("*Remove-Item*", "rm") and process.args : ("*ConsoleHost_history.txt*", "*(Get-PSReadlineOption).HistorySavePath*")) or
     (process.args : "*Set-PSReadlineOption*" and process.args : "*SaveNothing*"))
```
Some adjusts

2021-11-25 16:18 UTC, Samirbous approved these changes
👍  maybe bump up the risk score to Medium.

2021-11-25 16:25 UTC, merged