[New Rule] Shadowcopy via Symlink
elastic/detection-rules pull request #1675
Opened 2021-12-26 05:12 UTC by austinsonger

## Issues

## Summary

Resolves #1493

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-12-29 13:29 UTC, w0rk3r requested changes
Left some comments

2021-12-29 13:29 UTC, w0rk3r commented on rules/windows/credential_access_shadowcopy_via_mklink.toml
> +Identifies when shadow copies storage symbolic link is created.
Needs some more context

2021-12-29 13:29 UTC, w0rk3r commented on rules/windows/credential_access_shadowcopy_via_mklink.toml
> +false_positives = ["System Administrator working with shadow copies"]
```suggestion
false_positives = ["Legitimate administrative activity related to shadow copies"]
```

2021-12-29 13:29 UTC, w0rk3r commented on rules/windows/credential_access_shadowcopy_via_mklink.toml
> +name = "Shadowcopy via mklink"
```suggestion
name = "Symbolic Link to Shadow Copy Created"
```

2021-12-29 13:29 UTC, w0rk3r commented on rules/windows/credential_access_shadowcopy_via_mklink.toml
> +process.args : "/D"
```suggestion
(process.args : "/D" or process.command_line : "*/D *")
```

2021-12-29 13:29 UTC, w0rk3r commented on rules/windows/credential_access_shadowcopy_via_mklink.toml
> +process.args : "/D"
The /c is from cmd, and using the "/D" alone will not alert when the command is put between quotes, so let's change it to this by now

2022-01-12 09:28 UTC, Samirbous approved these changes

2022-01-12 09:28 UTC, Samirbous commented on rules/windows/credential_access_symbolic_link_to_shadow_copy_createdcredential_access_symbolic_link_to_shadow_copy_created.toml
> +(process.args : "/D" or process.command_line : "*/D *")
```suggestion
process where event.type in ("start", "process_started") and
process.pe.original_file_name == "Cmd.Exe" and
process.args : "*mklink*" and
process.args : "*\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy*"
```

2022-01-12 10:52 UTC, merged