[Rule Tuning] O365 Excessive Single Sign-On Logon Errors
elastic/detection-rules pull request #1680
Opened 2021-12-30 21:41 UTC by trevormiller6

The original rule had the event.category as "web" the correct value is "authentication".

![SsoArtifactInvalidOrExpired](https://user-images.githubusercontent.com/22669390/147789568-64f2f679-e59c-43bc-ab3b-4bd490397151.png)

2021-12-30 22:08 UTC, w0rk3r requested changes
Hey @trevormiller6, thanks for the PR! It is always nice to see new people contributing ;)
Can you bump the updated_date field?

2021-12-30 22:22 UTC, trevormiller6 commented
@w0rk3r Thanks. I just pushed the change.

2021-12-30 22:33 UTC, w0rk3r approved these changes
LGTM, looking forward to your next contributions ;)

2022-01-20 08:04 UTC, Samirbous approved these changes

2022-01-20 11:32 UTC, merged