Change default time query for rounding days
elastic/detection-rules pull request #1713
Opened 2022-01-24 12:18 UTC by nkhristinin

To improve cache performance for the IM rule we have ideas to round the timestamp query by days.

From @timestamp >= "now-30d" - to @timestamp >= "now-30d/d"

2022-01-24 12:23 UTC, w0rk3r commented
(`updated_date` needs to be updated)

2022-01-25 00:15 UTC, ecezalp approved these changes
LGTM

2022-01-26 23:26 UTC, brokensound77 commented on rules/cross-platform/threat_intel_filebeat7x.toml
> +updated_date = "2022/01/26"
This rule was deprecated for 8.0+ #1703, which is why there is a conflict. You can revert the changes on this file to resolve the conflict.

Then, in a separate PR targeting 7.16, this file can be changed with this update and then backported to 7.14-7.15 (and maybe 7.13, depending on when the rule was introduced)

2022-01-26 23:27 UTC, brokensound77 requested changes
https://github.com/elastic/detection-rules/pull/1713/files#r793134842

2022-01-26 23:32 UTC, brokensound77 commented on rules/cross-platform/threat_intel_filebeat7x.toml
> +updated_date = "2022/01/26"
for more context, you can see:
* 8.0 (and main) [deprecated](https://github.com/elastic/detection-rules/blob/8.0/rules/_deprecated/threat_intel_filebeat7x.toml)
* 7.13 (-7.16) [production](https://github.com/elastic/detection-rules/tree/7.13/rules/cross-platform)

2022-01-27 18:52 UTC, brokensound77 approved these changes
Thanks for the changes - LGTM 👍

2022-01-28 19:34 UTC, merged