[New Rule] AWS KMS CMK Disabled or Scheduled for Deletion
elastic/detection-rules pull request #2318
Opened 2022-09-21 16:00 UTC by xavigpich

## Issues
https://github.com/elastic/detection-rules/issues/2086

## Summary
Detects an attempt to disable or schedule for deletion of an AWS KMS Customer Managed Key (CMK).

Deleting an AWS KMS key is destructive and potentially dangerous. It deletes the key material and all metadata associated with the KMS key and is irreversible. After a KMS key is deleted, you can no longer decrypt the data that was encrypted under that KMS key, which means that data becomes unrecoverable.

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? Yes

2022-10-14 13:47 UTC, w0rk3r requested changes
Hey @xavigpich, what a nice first contribution! I left some comments and changes, but feel free to ask for clarification if needed. Thanks!

PS: Looking forward to your next awesome contribution

2022-10-14 13:47 UTC, w0rk3r commented on rules/integrations/aws/impact_kms_cmk_disabled_or_scheduled_for_deletion.toml
> +
I think we can remove this one

2022-10-14 13:47 UTC, w0rk3r commented on rules/integrations/aws/impact_kms_cmk_disabled_or_scheduled_for_deletion.toml
> +rule_id = "x135f0du-po0z-47c7-2f6f-qsfp1x7cca9n"
```suggestion
rule_id = "6951f15e-533c-4a60-8014-a3c3ab851a1b"
```
I don't think this is a valid GUID as it contains non-hex chars

2022-10-16 10:01 UTC, xavigpich commented
Hi @w0rk3r , I appreciate your positive feedback. I've updated the PR with your suggestions. Thanks!

2022-10-17 12:57 UTC, w0rk3r approved these changes
Some nits, otherwise LGTM. Thanks!

2022-10-17 12:57 UTC, w0rk3r commented on rules/integrations/aws/impact_kms_cmk_disabled_or_scheduled_for_deletion.toml
> +    and/or hostname should be making changes in your environment. Log stream deletions by unfamiliar users should be investigated. If known
>  Log stream deletions by unfamiliar users should be investigated.

This needs to be adjusted to this rule.

2022-10-17 12:57 UTC, w0rk3r commented on rules/integrations/aws/impact_kms_cmk_disabled_or_scheduled_for_deletion.toml
> +name = "AWS KMS Customer Managed Key Disabled or Scheduled For Deletion"
```suggestion
name = "AWS KMS Customer Managed Key Disabled or Scheduled for Deletion"
```
nit

2022-10-18 09:29 UTC, w0rk3r commented
@xavigpich I think your AV solution deleted the [rta/bin/Installer.msi](https://github.com/elastic/detection-rules/pull/2318/files#diff-00ff656a882eef47a11bee96328a8dabce83b699c09e2454c64ec29299ba05e0) file, can you revert it?

2022-10-20 08:44 UTC, xavigpich commented
> This is a great addition to our AWS ruleset. @xavigpich thank you for contributing! Once `installer.msi` is put back, I will approve.

The Installer.msi is back. Apologies for that

2022-10-20 17:22 UTC, w0rk3r commented on rules/integrations/aws/impact_kms_cmk_disabled_or_scheduled_for_deletion.toml
> +name = "AWS KMS Customer Managed Key Disabled or Scheduled For Deletion"
```suggestion
name = "AWS KMS Customer Managed Key Disabled or Scheduled for Deletion"
```

2022-10-20 17:29 UTC, merged