add "Windows Azure Linux Agent"'s pid file to list
elastic/detection-rules pull request #2328
Opened 2022-09-23 18:42 UTC by alexcote1

## Summary

https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/agent-linux this tool is default installed on azure linux hosts, can resolve my problem as an exception and have but the tool is common enough in cloud environments that it deserves inclusion in my opinion.

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? (yes)

2022-09-23 21:26 UTC, w0rk3r requested changes
Hey @alexcote1, thank you for the contribution!

Can you bump the `updated_date` field on this one?

2022-09-26 13:19 UTC, w0rk3r commented on rules/linux/execution_abnormal_process_id_file_created.toml
> +updated_date = "2022/9/23"
```suggestion
updated_date = "2022/09/23"
```

2022-09-26 13:19 UTC, w0rk3r approved these changes

2022-10-05 16:47 UTC, terrancedejesus approved these changes
Thanks for your contribution, this looks good to me!

2022-10-13 19:53 UTC, merged