[Rule Tuning] Potential Shell via Web Server
elastic/detection-rules pull request #2585
Opened 2023-02-21 15:42 UTC by Aegrah

## Summary
Identifies suspicious commands executed via a web server, which may suggest a vulnerability and remote shell access.

The previous rule was written in KQL, and missed several web shells initiated by process.name such as "sh". Converted to rule to EQL and added several extra processes to detect.

### Detection Logic
<img width="1615" alt="image" src="https://user-images.githubusercontent.com/78494512/220390870-ccf22030-ecf7-4557-a488-96af1a9c8f58.png">

2023-02-21 16:27 UTC, Aegrah commented
Will change this to draft untill issue #1730 is resolved.

2023-02-22 12:40 UTC, shashank-elastic requested changes

2023-02-22 12:40 UTC, shashank-elastic commented on rules/linux/persistence_linux_shell_activity_by_web_server.toml
> +language = "eql"
We had a discussion of  https://github.com/elastic/detection-rules/issues/1730
And this was something that was brought and made aware type changing is not an option.

2023-02-22 12:40 UTC, shashank-elastic commented on rules/linux/persistence_linux_shell_activity_by_web_server.toml
> +rule_id = "b7b2c320-d4db-4f8e-8f92-83f9d0c3e6a4"
Instead of bypassing by overwriting a rule_id
I would say deprecate the older rule and create a new rule with this EQL.

@DefSecSentinel / @brokensound77  to double-check if this approach is feasible and does not break anything from Kibana. Per my understanding, this could be the best possible approach

2023-02-22 13:58 UTC, Aegrah commented on rules/linux/persistence_linux_shell_activity_by_web_server.toml
> +rule_id = "b7b2c320-d4db-4f8e-8f92-83f9d0c3e6a4"
I didn't just change the rule ID, I removed the old file, and added the new one. The change in rule_id isn't the bypass. See commit ([e994b62](https://github.com/elastic/detection-rules/pull/2585/commits/e994b62ecb838f73fa56d145e529169ebd2f5133)). Currently, our only approach seems to be what you just suggested - which is removing the old file, and creating a new one.

2023-02-22 14:00 UTC, shashank-elastic commented on rules/linux/persistence_linux_shell_activity_by_web_server.toml
> +rule_id = "b7b2c320-d4db-4f8e-8f92-83f9d0c3e6a4"
I would still suggest a clean deprecation and addition on new file as a new rule.

2023-02-28 15:23 UTC, imays11 commented on rules/linux/persistence_linux_shell_activity_by_web_server.toml
> +process.name : ("bash", "sh", "ash", "dash", "zsh", "rbash", "csh", "ksh", "tmux", "python*", "perl*", "php*") and
```suggestion
process.name : ("bash", "sh", "ash", "dash", "zsh", "rbash", "csh", "tcsh", "ksh", "tmux", "python*", "perl*", "php*") and
```
Nice additions, added one more

2023-03-01 00:29 UTC, brokensound77 commented on rules/linux/persistence_linux_shell_activity_by_web_server.toml
> +rule_id = "b7b2c320-d4db-4f8e-8f92-83f9d0c3e6a4"
@Aegrah if you run `python -m detection_rules dev deprecate-rule` on the old file, it will take care of moving and updating the original file

2023-03-01 00:29 UTC, brokensound77 commented on rules/linux/persistence_linux_shell_activity_by_web_server.toml
> +process.args:("whoami*", "id", "uname*", "cat*", "hostname*", "ip*", "curl*", "wget*", "pwd") and
```suggestion
process.args : ("whoami*", "id", "uname*", "cat*", "hostname*", "ip*", "curl*", "wget*", "pwd") and
```

2023-03-01 00:31 UTC, brokensound77 commented on rules/linux/persistence_linux_shell_activity_by_web_server.toml
> +process.parent.name : ("apache", "apache2", "nginx", "httpd", "php*", "www", "www-data", "lighttpd", "caddy") and
how would you feel about using `process.parent.executable` with some default install locations of these from package managers. It would allow you to avoid the exclusions below (at least `not process.executable ...`)

2023-03-04 11:43 UTC, Aegrah commented
@shashank-elastic I reverted my commits, and deprecated the old rule, created the new one with type eql.

@brokensound77 I applied your formatting fix and your suggestion to add process.parent.executables instead of names. This will indeed minimize false positives, thanks for the good suggestion. 

@imays11 I added the "*sh" to process.name to catch all shells ending with "sh", is a useful wildcard query to make the query easier to read and more effective at the same time, so your suggestion is also included in the new rule.

@DefSecSentinel I looked into the Kraken web shell, but the only info we can currently capture are TCP connection events initiated by the host that is exploiting the web server, thus with our current capabilities it is difficult to detect. Will require further investigation to see how we can improve on this. Currently setting up an IIS environment to see whether we can capture more data in Windows environments (this PR however is focused on Linux). 

@everyone thanks for the help.

2023-03-06 19:28 UTC, imays11 approved these changes

2023-03-20 11:19 UTC, w0rk3r commented on rules/linux/persistence_shell_activity_via_web_server.toml
> +index = ["auditbeat-*", "logs-endpoint.events.*"]
We need to test this one to see if it is Endgame compatible, if not, we should remove the Endgame tag

2023-03-20 11:19 UTC, w0rk3r commented on rules/linux/persistence_shell_activity_via_web_server.toml
> +index = ["auditbeat-*", "logs-endpoint.events.*"]
Also, would be interesting to test this with Auditbeat too, and remove or add setup instructions as needed

2023-03-22 12:21 UTC, Aegrah commented
This PR is using the new OSQuery investigation guide layout. Will have to wait until #2602 is merged before unit testing will no longer fail. In the meanwhile - investigation guide feedback is always welcome.

2023-04-17 13:08 UTC, w0rk3r commented on rules/linux/persistence_linux_shell_activity_via_web_server.toml
> +  - Investigate the process tree spawned from the user that is used to run the web application service. A user that is running a web application should not spawn other child processes.
```suggestion
  - Investigate the process tree spawned from the user that is used to run the web application service. A user that is running a web application should not spawn other child processes.
```
This one is a bit unclear, should it not run other processes, or it shouldn't have any child processes on the webserver one?

2023-04-17 13:08 UTC, w0rk3r commented on rules/linux/persistence_linux_shell_activity_via_web_server.toml
> +  - Investigate the process tree spawned from the user that is used to run the web application service. A user that is running a web application should not spawn other child processes.
Maybe sharing the same user to handle other server tasks and applications could be very common

2023-04-17 13:08 UTC, w0rk3r commented on rules/linux/persistence_linux_shell_activity_via_web_server.toml
> +If enabling an EQL rule on a non-elastic-agent index (such as beats) for versions <8.2, events will not define `event.ingested` and default fallback for EQL rules was not added until 8.2, so you will
```suggestion
```
This one will not backport that far

2023-05-05 07:47 UTC, merged