New Rule to identify iptables or firewall disabling.
elastic/detection-rules pull request #2591
Opened 2023-02-22 18:18 UTC by shashank-elastic

## Issues
#2590 

## Summary
The rule was in endpoint and is being moved to detection mode as part of elastic/endpoint-rules/issues/1817
No additional testing is required. Tested as part of elastic/endpoint-rules/pull/1297

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2023-02-22 19:43 UTC, DefSecSentinel approved these changes
LGTM

2023-02-22 19:44 UTC, brokensound77 commented on rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml
> +process where event.action == "exec" and
```suggestion
process where event.type == "start" and event.action == "exec" and
```

2023-02-22 19:45 UTC, brokensound77 commented on rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml
> +     (process.name == "ufw" and process.args : "disable") or
```suggestion
     (process.name == "ufw" and process.args == "disable") or
```

2023-02-22 19:45 UTC, brokensound77 commented on rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml
> +     (process.name == "iptables" and process.args : "-F" and process.args_count <= 2)
```suggestion
     (process.name == "iptables" and process.args == "-F" and process.args_count == 2)
```

2023-02-22 19:46 UTC, brokensound77 commented on rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml
> +       (process.name=="systemctl" and process.args in ("disable","stop","kill"))) and
```suggestion
       (process.name == "systemctl" and process.args in ("disable", "stop", "kill"))) and
```

2023-02-22 19:46 UTC, brokensound77 commented on rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml
> +    process.args in ("firewalld","ip6tables","iptables")
```suggestion
    process.args in ("firewalld", "ip6tables", "iptables")
```

2023-02-22 19:48 UTC, brokensound77 requested changes
This is almost identical to this [deprecation](https://github.com/elastic/detection-rules/blob/f17b6f17023aa78cd5fea443ecb31a7df631f046/rules/_deprecated/defense_evasion_attempt_to_disable_iptables_or_firewall.toml#L27). What is different that justifies adding it back?

2023-02-23 13:00 UTC, shashank-elastic commented
> This is almost identical to this [deprecation](https://github.com/elastic/detection-rules/blob/f17b6f17023aa78cd5fea443ecb31a7df631f046/rules/_deprecated/defense_evasion_attempt_to_disable_iptables_or_firewall.toml#L27). What is different that justifies adding it back?

The deprecation issue in the endpoint had the details, Pinning it here. elastic/endpoint-rules/issues/1817
Analysis of the Telemetry showed that a rule is being fired for both script executions and bash executions, and filtering out script executions would reduce the hits but won't be a precise decision to prevent the actions.

So at any point, this can never be a perfect prevention scenario. Regular operations scripts can use these commands that can lead to False positive alerts and killing them would not be a favorable option to the user.  
But we would still want to expose the ability to monitor the network changes on the host to the user and hence move this to the detection criteria.

The alert is not noisy in terms of hits ( 11 hits for 24 hrs and 200 hits for 30 days period) it can lead to a nonmalicious process being killed when the prevention action is executed if this rule gets promoted in the endpoint.

2023-02-28 14:48 UTC, imays11 approved these changes
Looks good 👍🏾

2023-03-01 03:32 UTC, brokensound77 commented
So, to verify @shashank-elastic, essentially you are saying that the original rule should have never been deprecated, but just tuned with `event.action == "exec"`?

2023-03-01 03:39 UTC, shashank-elastic commented
@brokensound77 I think you have picked one point of consideration and left the other, 
Let me put it back here

> The majority of the previous hits were for allowing activities of ufw command, this primary category can fall into infra scripts using them for operational changes or deployments. This is already eliminated and we monitor only disable and stop cases for greater granularity.

The above change has helped even more than the exec tuning. Is it a tight fit rule yet, no we can still find hits of infrastructure scripts trying to disable , so once we soak this rule, we can eliminate those from executable path filters to make it even better.

2023-03-01 06:46 UTC, brokensound77 commented
Ah I missed that, thanks, I updated my comment

2023-03-01 06:48 UTC, brokensound77 commented
You can proceed with processing this rule. I am not blocking anything, just wanted to ensure we had the conversation, given the unique circumstance. Thanks for the info 👍

2023-03-01 11:44 UTC, merged