[Interactive Terminal Spawned via Python] Add Query Exceptions for Update Package Installations
elastic/detection-rules pull request #2829
Opened 2023-06-05 21:07 UTC by MakoWish

## Issues
- Closes #2828 

## Summary
Adds query exceptions for package update scripts when using `yum update`. 

## Contributor checklist

- [X] Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- [X] Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2023-06-07 20:58 UTC, MakoWish commented
/test

2023-06-12 22:28 UTC, MakoWish commented
Pinging @w0rk3r

2023-06-19 15:46 UTC, shashank-elastic requested changes

2023-06-19 15:46 UTC, shashank-elastic commented on rules/linux/execution_python_tty_shell.toml
> +   not (process.args == "/bin/yum" and process.args == "update") and
This would eliminate one of the few possible false positives, please use the sample tuned query pinned in the issue to test on your work load.

2023-06-21 16:04 UTC, MakoWish commented
Closing in favor of #2859

2023-06-21 16:04 UTC, closed without merging