[New Rule] Suspicious Proc Enumeration
elastic/detection-rules pull request #2845
Opened 2023-06-09 09:19 UTC by Aegrah

## Summary
This PR proposes a new rule to identify suspicious proc pseudo file system enumeration. This threshold rule monitors for a rapid enumerations of 25 different proc cmd, stat, and exe files, which suggests an abnormal activity pattern. Such behavior could be an indicator of a malicious process scanning or gathering information about running processes, potentially for reconnaissance, privilege escalation, or identifying vulnerable targets. 

By using a threshold rule we can leverage the cardinality functionality to make sure that the process is actually enumerating several different proc file paths, and thus different processes. This is abnormal behavior. 

## Auditd Manager Setup Guide
As there was no `auditd manager` setup guide available yet, I wrote a new one. Please comment on how to improve this set up guide, and I will add the improvements to all upcoming auditd manager related rules.

## Detection 
```
host.os.type : "linux" and event.category : "file" and event.action : "opened-file" and 
file.path : (/proc/*/cmdline or /proc/*/stat or /proc/*/exe) and not process.parent.pid : 1

[rule.threshold]
field = ["host.id", "process.pid", "process.name"]
value = 1
[[rule.threshold.cardinality]]
field = "file.path"
value = 25
```
<img width="2551" alt="image" src="https://github.com/elastic/detection-rules/assets/78494512/506950a4-b7be-4166-b01a-f23c94c84ba8">

`pkill` was spawned from `sample.elf`, which is also malicious. This rule was tested in another cluster running several Linux servers, and generated FP's for 1 process. Exclusions can be made on per-environment basis. 

## Malware Analysis
These rules are found to be triggered by real malware samples, which @1337-42  and I have been detonating and analysing. Updates will be added to [#105](https://github.com/elastic/elastic-security-labs/issues/105).

2023-06-12 22:21 UTC, imays11 approved these changes
Nice use of threshold for this rule

2023-06-12 22:21 UTC, imays11 commented on rules/linux/discovery_suspicious_proc_enumeration.toml
> +This rule monitors for a rapid enumerations of 25 different proc cmd, stat, and exe files, which suggests an abnormal
```suggestion
This rule monitors for a rapid enumeration of 25 different proc cmd, stat, and exe files, which suggests an abnormal 
```

2023-06-14 11:05 UTC, eric-forte-elastic requested changes

2023-06-14 11:05 UTC, eric-forte-elastic commented on rules/linux/discovery_suspicious_proc_enumeration.toml
> +value = 25
```suggestion
value = 25

```

2023-07-03 13:17 UTC, eric-forte-elastic approved these changes

2023-07-04 09:34 UTC, merged