[FR] Add ES|QL Custom Library for Rule Support
elastic/detection-rules pull request #3134
Opened 2023-09-26 14:02 UTC by terrancedejesus

## Issue

Resolves https://github.com/elastic/ia-trade-team/issues/186

## Overview
This is a temporary dev branch for ES|QL exploration and custom library implementation. This PR is meant to stay in draft but serve as delta visualization for ES|QL library implementation and dev.

Related: https://github.com/elastic/ia-trade-team/issues/172

2023-11-27 22:10 UTC, Mikaayenson commented on detection_rules/devtools.py
> +    antlr_file = Path(get_path('detection_rules')) / 'etc' / 'antlr-4.13.1-complete.jar'
Reminder to delete this.

2023-11-27 22:17 UTC, Mikaayenson commented
## Update Nov 27
There is still much to do. Just opening the initial changes with semantic validation and parser generated via antlr4. Some antlr4 files from the initial commit will be removed later.

2023-11-28 17:35 UTC, Mikaayenson commented on rules/linux/credential_access_credential_dumping_via_unshadow.toml
> +[metadata]
⚠️ DO NOT MERGE WITH THIS RULE ⚠️

2023-11-29 02:08 UTC, Mikaayenson commented on esql/esql_listener.py
> +                return 'boolean'
Need to check these other ecs types

2023-12-05 02:09 UTC, Mikaayenson commented on rules/integrations/okta/initial_access_success_okta_sso_esql.toml
> +[metadata]
⚠️ Reminder to self: DELETE THIS FILE ⚠️

2023-12-05 02:09 UTC, Mikaayenson commented on tests/test_esql_rules.py
> +            # returns 0 because count on non-forwarded field process.parent.name
Sample unit tests not yet supported.

2024-01-23 14:04 UTC, eric-forte-elastic commented
> This is a temporary dev branch for ES|QL exploration and custom library implementation. This PR is meant to stay in draft but serve as delta visualization for ES|QL library implementation and dev.

Should this PR be put back into draft?

2024-01-29 14:50 UTC, eric-forte-elastic requested changes

2024-01-29 14:50 UTC, eric-forte-elastic commented on esql/utils.py
> +# def pretty_print_tree(ctx: EsqlBaseParser.SingleStatementContext, indent: int = 0, is_last: bool = True):
Reminder, I think we can remove these commented out function headers and add the type hinting to the active headers? 
```suggestion

```

2024-04-14 16:13 UTC, closed without merging