Unusual Process Calling the Metadata Service [Linux]
elastic/detection-rules pull request #321
Opened 2020-09-22 18:24 UTC by randomuserid

## Issues

https://github.com/elastic/mechagodzilla/issues/102

## Summary

ML rule for the Linux version of the job that looks for rare process name calling the metadata service

2020-09-22 19:05 UTC, devonakerr approved these changes

2020-09-22 20:19 UTC, bm11100 requested changes

2020-09-22 20:19 UTC, bm11100 commented on rules/ml/ml_linux_anomalous_metadata_process.toml
> +maturity = "development"
```suggestion
maturity = "production"
```

2020-09-22 20:19 UTC, bm11100 commented on rules/ml/ml_linux_anomalous_metadata_process.toml
> +false_positives = ["A newly installed program or one that runs very rarely as part of a monthly or quarterly workflow could trigger this detection rule."]
needs linting

2020-09-23 19:27 UTC, bm11100 approved these changes

2020-09-23 19:29 UTC, merged