[Tuning & New Rule] Linux Reverse Shell & DR Tuning
elastic/detection-rules pull request #3254
Opened 2023-11-02 09:27 UTC by Aegrah

## Summary
This PR tunes some Linux DRs and adds one additional reverse shell rule to the set that is tested in ER.

2023-11-02 15:19 UTC, shashank-elastic requested changes

2023-11-02 15:19 UTC, shashank-elastic commented on rules/linux/execution_shell_via_child_tcp_utility_linux.toml
> +setup = """
```suggestion
setup = """

This rule requires data coming in from one of the following integrations:
- Elastic Defend

### Elastic Defend Integration Setup
Elastic Defend is integrated into the Elastic Agent using Fleet. Upon configuration, the integration allows the Elastic Agent to monitor events on your host and send data to the Elastic Security app.

#### Prerequisite Requirements:
- Fleet is required for Elastic Defend.
- To configure Fleet Server refer to the [documentation](https://www.elastic.co/guide/en/fleet/current/fleet-server.html).

#### The following steps should be executed in order to add the Elastic Defend integration on a Linux System:
- Go to the Kibana home page and click "Add integrations".
- In the query bar, search for "Elastic Defend" and select the integration to see more details about it.
- Click "Add Elastic Defend".
- Configure the integration name and optionally add a description.
- Select the type of environment you want to protect, either "Traditional Endpoints" or "Cloud Workloads".
- Select a configuration preset. Each preset comes with different default settings for Elastic Agent, you can further customize these later by configuring the Elastic Defend integration policy. [Helper guide](https://www.elastic.co/guide/en/security/current/configure-endpoint-integration-policy.html).
- We suggest selecting "Complete EDR (Endpoint Detection and Response)" as a configuration setting, that provides "All events; all preventions"
- Enter a name for the agent policy in "New agent policy name". If other agent policies already exist, you can click the "Existing hosts" tab and select an existing policy instead.
For more details on Elastic Agent configuration settings, refer to the [helper guide](https://www.elastic.co/guide/en/fleet/8.10/agent-policy.html).
- Click "Save and Continue".
- To complete the integration, select "Add Elastic Agent to your hosts" and continue to the next section to install the Elastic Agent on your hosts.
For more details on Elastic Defend refer to the [helper guide](https://www.elastic.co/guide/en/security/current/install-endpoint.html).

"""
```

2023-12-08 03:05 UTC, terrancedejesus commented on rules/_deprecated/execution_shell_suspicious_parent_child_revshell_linux.toml
> +maturity = "deprecated"
Why the deprecation?

2023-12-08 03:07 UTC, terrancedejesus commented on rules/linux/execution_shell_via_background_process.toml
> +tags = [
I'd vote to roll back this change. While minor, it will bump the rule version and be received as a major rule update since version bump +1.

2023-12-08 03:11 UTC, terrancedejesus commented on rules/linux/execution_shell_via_child_tcp_utility_linux.toml
> +#### The following steps should be executed in order to add the Elastic Defend integration on a Linux System:
This is very nice and detailed, but I wonder about sustainability. With changes to the UI every minor, we may create unwanted debt by including this throughout the ruleset. We could always point to the docs sight for Defend and rely upstream on the integration owners to keep docs updated.

Maybe we good question for the next team or area meeting to discuss.

2023-12-08 03:30 UTC, terrancedejesus commented on rules/linux/execution_shell_via_tcp_cli_utility_linux.toml
> +     (process.args : ("-i", "-l")) or (process.parent.name == "socat" and process.parent.args : "*exec*")
Logic seems relatively close to `Potential Reverse Shell via Child`. Do we need to have separate rules if so closely related?

2023-12-08 03:32 UTC, terrancedejesus approved these changes
@Aegrah great work! I left some questions and suggestions but am approving either way to not become a blocker. 👍🏽

2023-12-11 12:36 UTC, Aegrah commented on rules/linux/execution_shell_via_child_tcp_utility_linux.toml
> +#### The following steps should be executed in order to add the Elastic Defend integration on a Linux System:
This was added by @shashank-elastic 's PRs. There were several, but as an example, this one: https://github.com/elastic/detection-rules/pull/3141. It was approved by our content manager, so I am just adding it to the new ones.

2023-12-14 11:43 UTC, eric-forte-elastic commented on rules/linux/execution_shell_via_child_tcp_utility_linux.toml
> +     (process.args : ("-i", "-l")) or (process.parent.name == "socat" and process.parent.args : "*exec*")
That is a good point, I think for most cases you are right that you would see the source process be something like `ssh`. 

Sounds good to me! :+1:

2023-12-14 11:44 UTC, eric-forte-elastic approved these changes

2023-12-18 08:36 UTC, merged