[FR] Add `elastic_last_update` to Rule Schema as a Build Time Field
elastic/detection-rules pull request #3427
Opened 2024-02-05 20:36 UTC by terrancedejesus

## Issues
* https://github.com/elastic/detection-rules/issues/2826

## Summary
This pull request adds `elastic_last_update` to the `BaseRuleSchema`, defies a minimum compatible stack for this field and dynamically generates it on rule loading. For more details, please refer to the issue referenced.

## Testing
TBD

2024-02-21 19:29 UTC, terrancedejesus commented on detection_rules/rule.py
> +    elastic_last_update: Optional[definitions.ElasticLastUpdateDate] = \
Updated. Good catch.

2024-02-21 19:32 UTC, terrancedejesus commented
@Mikaayenson - When working on DaC and `import-rules`, we should consider build time fields and implications in general when re-factoring this.

2024-02-21 19:56 UTC, brokensound77 requested changes
I think this is one of those times where, this arguably solves the problem we are aiming to solve, but with risks and ambiguity that may not justify it. IOW, potentially saying _no_ to a good idea based on present and future implications.

This sets a precedent that I think introduces risk and ambiguity. This is something we have aimed to explicitly avoid in the past. A much safer approach would be to just add it as another field to the schema, populated by rule author -- or even at version lock time, where we grab the last commit time and insert it as a build time field.

Exempting fields from the calculation breaks the requirements of a build time field (which is why the exemption is needed).

It seems like all approaches have some kind of tradeoff to them, so there is no perfect solution, I just don't know that this is the _best_ solution.

I know we have discussed this a ton, but I am blocking based on the need for further discussion and the implications of this approach

2024-02-21 20:05 UTC, terrancedejesus commented
@brokensound77 - Happy to continue discussion more. Please let me know when you have time.

2024-02-23 20:33 UTC, Mikaayenson commented
### Update Feb 23
After speaking with D&R, another reason to hold on this is they anticipate more changes. It’s still unclear if they want to have a top-level field `source_updated_at` or an object with a field `source.updated_at` to make it future-proof.  

So much more to come after our time away.

2024-02-28 15:58 UTC, Mikaayenson commented
## Update 28

Speaking with @terrancedejesus and @brokensound77 at EAH, here's the gist of how we can handle this:
- Treat the new field as a breaking change (don't push the schema updates until version+3 release is here)
- We also need to consider that global breaking changes introduce 1100+ rules into the rules package because of historical rules.

@banderror Alternatively is it possible on your end to either:
1. Not be able export the new field when a rule is exported OR
2. Just pull the field from our metadata section (we would our updated date to the metadata)

2024-03-14 15:35 UTC, Mikaayenson commented
### Update Mar 14 - Simplified Protections Sync

- We're going to hold until 8.15 to release this.
- We don't need to update schemas are worry about import/export. The field will not be exported. It only needs to be dynamically generated and pushed on package release.

2024-08-01 13:04 UTC, Mikaayenson commented
### Update Aug 1

After speaking with @approksiu, we need to hold off until end of year until the rules management team is able to discuss further.

2024-08-01 13:10 UTC, shashank-elastic commented
Removing this from Q2 docket

2024-12-19 18:21 UTC, terrancedejesus commented
Closing this pull request, but keeping the issue open for when we discuss with @banderror regarding this requirement.

2024-12-19 18:21 UTC, closed without merging