[Rule Tuning] Tuning `Direct Outbound SMB Connection`
elastic/detection-rules pull request #3485
Opened 2024-03-03 19:15 UTC by terrancedejesus

## Issues
* https://github.com/elastic/detection-rules/issues/3473

## Summary
This pull request attempts to tune the `Direct Outbound SMB Connection` rule for performance and efficacy.
The following was taken into consideration when tuning this rule:

* Is the lookback time window `from` adequate for capturing the intended events related to this threat
* For indexes defined, can they be scoped tighter related the the event categories specified in the query
* If this is an EQL sequence query, can it be adjusted to a non-sequence query
* If this is an EQL sequence query, is a maxspan defined and can it be adjusted to reduce the volume of events captured by still capturing events related to the threat
* If this is an EQL sequence query, can the first sequence be adjusted to reduce the volume of events captured and held in memory before the next sequence by adding additional filters
* If this is an EQL sequence query, can each sequence be adjusted to filter out noise or false-positives that contribute to a high volume of events held in memory
* If the join is for `process.entity_id` can we add an `until` operation explicitly for the process ending to stop searching when necessary

A `### Performance` header has been added to the `note` value to explain our understanding of potential performance impact from this query due to the detection logic in each sequence.

2024-04-02 09:44 UTC, w0rk3r commented on rules/windows/lateral_movement_direct_outbound_smb_connection.toml
> +  ]
```suggestion
      process.args :"?:\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection\\Downloads\\PSScript_*.ps1")]
```

2024-04-02 09:44 UTC, w0rk3r commented on rules/windows/lateral_movement_direct_outbound_smb_connection.toml
> +  ]
>/* filter out anything trusted but not from Microsoft */
>/* LOLBins will be inherently trusted and signed, so ignore everything else trusted */

2024-04-02 09:44 UTC, w0rk3r commented on rules/windows/lateral_movement_direct_outbound_smb_connection.toml
> +    destination.ip != "localhost"]
```suggestion
      "::1", "FE80::/10", "FF00::/8")
```

2024-04-02 10:44 UTC, Samirbous requested changes

2024-04-02 10:45 UTC, Samirbous commented on rules/windows/lateral_movement_direct_outbound_smb_connection.toml
> +### Performance
its good to have a description of the performance impact reasoning, but for users who want to enable/disable certain rules via rules management GUI they will need a faster way to do so, tags maybe ?

2024-08-07 14:00 UTC, terrancedejesus commented on rules/windows/lateral_movement_direct_outbound_smb_connection.toml
> +    /* ignore SMB traffic destined internally */
The original name suggests egress SMB traffic via LOLBins, but the description includes lateral movement as well. If we keep the scope for internal, then I'll rename the rule and description appropriately, while removing this exclusion.

2024-08-07 15:13 UTC, terrancedejesus commented
I've made rule name and description adjustments, while adding comments to the query.
Looking for FPs in telemetry, ~90% are from executables related to ZOHO corporations that make more sense to be a customer exception, rather than exclusion in our rule. Other than this, the volume is relatively low for this rule. 

Image below shows out of ~3k global alerts, ~90% are related to code signatures for ZOHO Corp.
<img width="1713" alt="Screenshot 2024-08-07 at 11 12 32 AM" src="https://github.com/user-attachments/assets/d37aaade-ca8c-4ade-91ba-06834b6b6349">

2024-08-08 14:53 UTC, Aegrah approved these changes

2024-08-13 17:04 UTC, w0rk3r approved these changes

2024-08-13 17:04 UTC, w0rk3r commented on rules/windows/lateral_movement_direct_outbound_smb_connection.toml
> +name = "Untrusted Non-Microsoft or LOLBin SMB Connections"
```suggestion
name = "SMB Connections via LOLBin or Untrusted Process"
```

2024-08-13 17:53 UTC, merged