Deprecate Releasing to a patch kibana version workflow
elastic/detection-rules pull request #3552
Opened 2024-04-01 13:19 UTC by shashank-elastic

## Issues
#3527

## Summary
- Depecrate Kibana Workflow commands in DR.
- We do not use this post 8.6 and with python upgrades we should not be maintaining this piece of code, we may encounter issues such as #3527.

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2024-04-01 13:22 UTC, terrancedejesus commented
I'd make sure to see where all of these CLI commands are referenced throughout the code, if they are, to ensure that upon deprecation we do not inadvertently effect other parts of the code.

2024-04-01 13:23 UTC, shashank-elastic commented
> I'd make sure to see where all of these CLI commands are referenced throughout the code, if they are, to ensure that upon deprecation we do not inadvertently effect other parts of the code.

Yes definitely will update the PR with those. I wanted to unblock my other PR https://github.com/elastic/detection-rules/pull/3528 as i need that for DR release tomo, so this was a quick one to show we are tracking the deprecation and that can make it to main!

2024-04-01 14:21 UTC, shashank-elastic commented
> I'd make sure to see where all of these CLI commands are referenced throughout the code, if they are, to ensure that upon deprecation we do not inadvertently effect other parts of the code.

We had a reference in MakeFile which was removed. I don't see any more references.

2024-04-01 15:00 UTC, eric-forte-elastic approved these changes
:green_circle: Manual review, looks good to me! :+1:

Great to clean up :rocket:

2024-04-01 15:00 UTC, Mikaayenson commented on detection_rules/devtools.py
> -def kibana_diff(rule_id, repo, branch, threads):
We should keep this.

2024-04-01 15:01 UTC, eric-forte-elastic commented on detection_rules/devtools.py
> -def kibana_diff(rule_id, repo, branch, threads):
Agreed!

2024-04-01 15:02 UTC, eric-forte-elastic requested changes
Let's add back `kibana-diff` otherwise looks good :+1:

2024-04-01 16:14 UTC, shashank-elastic commented on detection_rules/devtools.py
> -def kibana_diff(rule_id, repo, branch, threads):
Reverted Back.

2024-04-01 19:36 UTC, eric-forte-elastic approved these changes
:green_circle: Manual review, looks good to me! :+1:

2024-04-02 03:38 UTC, Mikaayenson approved these changes
LGTM

2024-04-02 13:35 UTC, terrancedejesus approved these changes

2024-04-03 03:04 UTC, merged