Adding setup templates to the ML rules
elastic/detection-rules pull request #3798
Opened 2024-06-18 13:43 UTC by sodhikirti07

## Issues
- https://github.com/elastic/ia-trade-team/issues/324

## Summary
This PR adds related setup template to the ML rules.

Setup template: [Setup Templates (ML rules)](https://docs.google.com/document/d/1EE0KpFf008AO_ee57ZUwuE_Njeud1ZESO3RvZ-pUGvQ/edit)

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2024-06-18 14:25 UTC, shashank-elastic requested changes

2024-06-18 14:25 UTC, shashank-elastic commented on rules/integrations/aws/ml_cloudtrail_error_message_spike.toml
> +setup = """## Setup
The note field, also has existing Setup information and the Unit tests are failing as there are 2 setup informations in Rule.  Please adjust these and remove the already existing setup information.

2024-06-18 14:25 UTC, shashank-elastic commented on rules/integrations/aws/ml_cloudtrail_error_message_spike.toml
> +setup = """## Setup
Please check this across all rules, and also update updated_date filed to reflect rule modification date.

2024-06-18 15:45 UTC, shashank-elastic approved these changes
Templates reviewed here https://github.com/elastic/ia-trade-team/issues/324#issuecomment-2165399171. 
This is implementation PR.

2024-06-18 18:07 UTC, jmcarlock approved these changes

2024-06-18 18:25 UTC, susan-shu-c approved these changes

2024-06-19 11:48 UTC, approksiu approved these changes
Apart from rules with 2 setup fields, LGTM.

2024-06-19 12:38 UTC, sodhikirti07 commented
> Apart from rules with 2 setup fields, LGTM.

@approksiu I've removed the second set of setup instructions from the rules.

2024-06-19 14:04 UTC, merged