Revert "[Bug] Handle formatting empty list"
elastic/detection-rules pull request #4087
Opened 2024-09-17 19:52 UTC by brokensound77

Reverts elastic/detection-rules#4086

This technically introduced a bug and will create opaque issues - most specifically when dumping a rule with empty lists then reparsing them (if required by the schema)

details:

https://github.com/elastic/detection-rules/pull/4086#issuecomment-2356772048

2024-09-17 20:14 UTC, Mikaayenson requested changes
Id either make the changes suggested [here](https://github.com/elastic/detection-rules/pull/4086#issuecomment-2356772048) or open a PR that will. Also if you have an example of this, can you share?

2024-09-19 22:10 UTC, brokensound77 commented
> Id either make the changes suggested [here](https://github.com/elastic/detection-rules/pull/4086#issuecomment-2356772048) or open a PR that will. Also if you have an example of this, can you share?

huh?

This isn't for resolving your original issue, it is to remove the faulty code that was introduced. Re-implementing a solution the proper way should occur in a dedicated PR, not alongside changes within a reverted commit

2024-09-19 22:49 UTC, Mikaayenson commented
> > Id either make the changes suggested [here](https://github.com/elastic/detection-rules/pull/4086#issuecomment-2356772048) or open a PR that will. Also if you have an example of this, can you share?
> 
> 
> 
> huh?
> 
> 
> 
> This isn't for resolving your original issue, it is to remove the faulty code that was introduced. Re-implementing a solution the proper way should occur in a dedicated PR, not alongside changes within a reverted commit

Do you have an example error or stack trace you can share? Steps to reproduce the error would be most helpful.

2024-11-25 23:46 UTC, closed without merging

2025-02-03 14:15 UTC, traut commented on detection_rules/rule_formatter.py
> +        if all(isinstance(i, dict) for i in v):
I think we can make it clearer! Reading the code, it's not obvious that this check will return `True` for an empty list / iterator, but it will:

```
In [1]: all([])
Out[1]: True

In [2]: all(x for x in [])
Out[2]: True
```

If that's desirable, we can make it explicit by doing

```
if len(v) == 0 or all(isinstance(i, dict) for i in v):
```