[New Rule] Suspicious Adobe Acrobat Updates Service Child Process
elastic/detection-rules pull request #886
Opened 2021-01-19 19:18 UTC by Samirbous

## Issues

Resolves https://github.com/elastic/detection-rules/issues/885

## Summary

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

2021-02-02 15:53 UTC, bm11100 commented on rules/macos/privilege_escalation_exploit_adobe_acrobat_updater.toml
> +                   /usr/sbin/installer)
```suggestion
event.category:process and event.type:(start or process_started) and
  process.parent.name:com.adobe.ARMDC.SMJobBlessHelper and
  user.name:root and
  not process.executable:
  (
    /Library/PrivilegedHelperTools/com.adobe.ARMDC.SMJobBlessHelper or
    /usr/bin/codesign or
    /private/var/folders/zz/*/T/download/ARMDCHammer or
    /usr/sbin/pkgutil or
    /usr/bin/shasum or
    /usr/bin/perl* or
    /usr/sbin/spctl or
    /usr/sbin/installer
  )
```

2021-02-02 15:53 UTC, bm11100 commented on rules/macos/privilege_escalation_exploit_adobe_acrobat_updater.toml
> +                   /usr/sbin/installer)
no query changes, just spacing

2021-02-02 15:53 UTC, bm11100 commented on rules/macos/privilege_escalation_exploit_adobe_acrobat_updater.toml
> +CVE-2020-9613 and verify that the impacted system is patched.
```suggestion
Detects attempts to exploit privilege escalation vulnerabilities related to the Adobe Acrobat Reader PrivilegedHelperTool
responsible for installing updates. For more information, refer to CVE-2020-9615, CVE-2020-9614 and
CVE-2020-9613 and verify that the impacted system is patched.
```

2021-02-02 15:53 UTC, bm11100 commented on rules/macos/privilege_escalation_exploit_adobe_acrobat_updater.toml
> +name = "Suspicious Adobe Acrobat Updates Service Child Process"
```suggestion
name = "Suspicious Child Process of Adobe Acrobat Reader Update Service"
```

2021-02-02 16:09 UTC, bm11100 approved these changes

2021-02-02 16:09 UTC, bm11100 commented on rules/macos/privilege_escalation_exploit_adobe_acrobat_updater.toml
> +false_positives = ["Trusted System or Adobe Acrobat Related Processes."]
```suggestion
false_positives = ["Trusted system or Adobe Acrobat Related processes."]
```

2021-02-09 17:25 UTC, threat-punter requested changes
Looks good but it looks like the linting was missed

2021-02-09 20:54 UTC, Samirbous commented
> Looks good but it looks like the linting was missed

I usually relint once I receive last comments/approvals (due to potential many changes in-between reviews)

2021-02-09 22:57 UTC, devonakerr approved these changes

2021-02-10 04:40 UTC, brokensound77 approved these changes
Query format change and 🚢

2021-02-10 04:40 UTC, brokensound77 commented on rules/macos/privilege_escalation_exploit_adobe_acrobat_updater.toml
> +  )
kql query whitespace is normalized at package generation time and so it is better to split them in a specific manner

```suggestion
event.category:process and event.type:(start or process_started) and
  process.parent.name:com.adobe.ARMDC.SMJobBlessHelper and
  user.name:root and
  not process.executable: (/Library/PrivilegedHelperTools/com.adobe.ARMDC.SMJobBlessHelper or
                           /usr/bin/codesign or
                           /private/var/folders/zz/*/T/download/ARMDCHammer or
                           /usr/sbin/pkgutil or
                           /usr/bin/shasum or
                           /usr/bin/perl* or
                           /usr/sbin/spctl or
                           /usr/sbin/installer)
```

2021-02-10 09:57 UTC, Samirbous commented
@threat-punter relinted :)

2021-02-10 13:08 UTC, merged

2021-02-10 13:43 UTC, threat-punter commented
> > Looks good but it looks like the linting was missed
> 
> 
> 
> I usually relint once I receive last comments/approvals (due to potential many changes in-between reviews)

Roger that @Samirbous. Thanks 👍